// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RpcData struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Args                 []interface{} `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	Errmsg               string   `protobuf:"bytes,4,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcData) Reset()         { *m = RpcData{} }
func (m *RpcData) String() string { return proto.CompactTextString(m) }
func (*RpcData) ProtoMessage()    {}
func (*RpcData) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0}
}

func (m *RpcData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcData.Unmarshal(m, b)
}
func (m *RpcData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcData.Marshal(b, m, deterministic)
}
func (m *RpcData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcData.Merge(m, src)
}
func (m *RpcData) XXX_Size() int {
	return xxx_messageInfo_RpcData.Size(m)
}
func (m *RpcData) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcData.DiscardUnknown(m)
}

var xxx_messageInfo_RpcData proto.InternalMessageInfo

func (m *RpcData) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RpcData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RpcData) GetArgs() []interface{} {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *RpcData) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func init() {
	proto.RegisterType((*RpcData)(nil), "proto.RpcData")
}

func init() { proto.RegisterFile("data.proto", fileDescriptor_871986018790d2fd) }

var fileDescriptor_871986018790d2fd = []byte{
	// 118 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x49, 0x2c, 0x49,
	0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x91, 0x5c, 0xec, 0x41, 0x05,
	0xc9, 0x2e, 0x89, 0x25, 0x89, 0x42, 0x7c, 0x5c, 0x4c, 0x99, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a,
	0xac, 0x41, 0x4c, 0x99, 0x29, 0x42, 0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x4c, 0x0a,
	0x8c, 0x1a, 0x9c, 0x41, 0x60, 0x36, 0x48, 0x2c, 0xb1, 0x28, 0xbd, 0x58, 0x82, 0x59, 0x81, 0x19,
	0x24, 0x06, 0x62, 0x0b, 0x89, 0x71, 0xb1, 0xa5, 0x16, 0x15, 0xe5, 0x16, 0xa7, 0x4b, 0xb0, 0x80,
	0x55, 0x42, 0x79, 0x49, 0x6c, 0x60, 0x1b, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe1, 0x21,
	0x8b, 0xa1, 0x76, 0x00, 0x00, 0x00,
}
